.ghcid, ema.cabal, flake.lock, flake.nix, src/Ema/Changing.hs, src/Ema/Example/Diary/2001-07-24.org, src/Ema/Example/Diary/2021-04-20.org, src/Ema/Example/Ex03_Diary.hs
=> Add Diary example using org-mode and fsnotify

bin/run-via-tmux, src/Ema/Example/Ex03_Diary.hs, src/Ema/Server.hs
Capture route click events and retrieve the page via websocket without a page reload.
Resolves #3
=> Smooth route click

README.md, docs/concepts.md, docs/concepts/logging.md, docs/guide/model.md, ema.cabal, flake.nix, src/Ema.hs, src/Ema/App.hs, src/Ema/Class.hs, src/Ema/Example/Ex02_Clock.hs, src/Ema/Example/Ex03_Documentation.hs, src/Ema/Generate.hs, src/Ema/Helper/FileSystem.hs, src/Ema/Server.hs
=> Add logging support

CHANGELOG.md, src/Ema/Asset.hs, src/Ema/Generate.hs
=> Support static files outside source directory

CHANGELOG.md, docs/guide/render.md, src/Ema/Route.hs
=> Add routeUrlWith

CHANGELOG.md, docs/concepts/cli.md, src/Ema/App.hs, src/Ema/CLI.hs
=> Remove -C option

ema.cabal, src/Ema/Helper/FileSystem.hs
For https://github.com/srid/emanote/issues/134
=> Deal with folder events by suggesting remount

src/Ema/Server.hs
This change allows the ema live-reloading server to be served from a non-root base path.
I reverse-proxy my emanote service behind Nginx from the location http://localhost/notes/. This is helpful because I have multiple `localhost` web servers running and I can't remember all their port numbers.
So in this example, the websocket URL should be `ws://localhost/notes/` rather than `ws://localhost`.
Also, any paths sent to the server for watching should have the `baseUrl` part removed.
=> Fix websocket URL when hosted under path

src/Ema/Server.hs
This is done with some simple changes in the javascript, no Haskell involved. I tested on my (currently unpublished) ema website and it seems to work as expected. I'm not sure if you would like to handle it in some other way.
=> Handle URL anchors (fixes #44)

ema.cabal, src/Ema/Server.hs
Builds on top of #83, and resolves #85 
Works on Chrome and Safari (Safari doesn't support smooth scrolling however).
=> Use scrollIntoView to scroll on anchor links

.ghcid, src/Ema/App.hs, src/Ema/CLI.hs, src/Ema/Server.hs
=> Use random port for live server, unless --port is passed

src/Ema/App.hs, src/Ema/Example/Ex02_Clock.hs, src/Ema/Example/Ex03_Store.hs, src/Ema/Example/Ex04_Multi.hs, src/Ema/Multi.hs, src/Ema/Multi/Generic/Example.hs, src/Ema/Route/Extra.hs, src/Ema/Site.hs
Resolves #94
cf. https://github.com/srid/emanote/pull/310
=> Remove route encoder argument from `siteInput`

src/Ema/Example/Ex01_Basic.hs, src/Ema/Example/Ex02_Clock.hs, src/Ema/Example/Ex03_Store.hs, src/Ema/Example/Ex04_Multi.hs, src/Ema/Generate.hs, src/Ema/Route/Encoder.hs, src/Ema/Route/Generic/Example.hs, src/Ema/Route/Lib/Folder.hs, src/Ema/Route/Lib/Multi.hs, src/Ema/Route/Url.hs, src/Ema/Server.hs, src/Ema/Site.hs, src/Optics/CtxPrism.hs
https://github.com/srid/ema/pull/93#discussion_r908437430
=> `siteOutput`: pass `Prism'` directly instead of `RouteEncoder`

ema.cabal, src/Ema/Route/Lib/Extra/MarkdownRoute.hs
Extracted from `ema-template` before it gets repurposed for a simpler template.
=> Add `MarkdownRoute` (extra)

www/ema-shim.js
Ref: https://github.com/EmaApps/ema/issues/69#issuecomment-1198463127
#69
=> websocket shim: Trigger events

flake.lock, flake.nix
Using https://github.com/srid/haskell-flake/pull/34
=> Use haskell-flake (multi-package API)

ema-extra/src/Ema/Route/Lib/Extra/PaginatedRoute.hs
=> Simplify `PaginatedRoute`

ema-generics/src/Ema/Route/Generic.hs, ema-generics/src/Ema/Route/Generic/RGeneric.hs, ema-generics/src/Ema/Route/Generic/Verification.hs, ema-generics/src/GHC/TypeLits/Extra/Symbol.hs, ema/README.md, flake.lock, flake.nix
=> Use GHC 9.2 only

ema/CHANGELOG.md, ema/ema.cabal, ema/src/Ema/Server.hs, ema/www/ema-shim.js
Almost the same as #151 but you can go through the diffs step by step in each commit.
=> Simplify websocket logic

ema-examples/src/Ema/Example/Ex06_Markdown.hs, ema-extra/src/Ema/Route/Lib/Extra/StaticRoute.hs, ema/CHANGELOG.md, ema/ema.cabal, ema/src/Ema/App.hs, ema/src/Ema/CLI.hs, ema/src/Ema/Site.hs
This simplifies the type so that we can implement #159 with a nicer API.
=> Ema.CLI.Action: unGADTify

ema/CHANGELOG.md, ema/www/ema-shim.js
Resolves https://github.com/srid/emanote/issues/511
=> Live server: allow pathname in anchor links

docs/tutorial/01-routes.md, docs/tutorial/02-model.md, docs/tutorial/03-dynamic.md
Just a couple things I noticed when going through the tutorial.
Cheers
=> docs: Small fixes to sample code in tutorial

docs/topics/hot-reload.md, ema/CHANGELOG.md, ema/ema.cabal, ema/src/Ema/Server/WebSocket/Options.hs, ema/www/ema-shim.js, flake.lock
=> Switch from morphdom -> idiomorph
